language: generic

services:
  - docker

before_install:
  - docker build -t sarvagnan/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true sarvagnan/react-test npm run test

after_success:
  - docker build -t sarvagnan/multi-client ./client
  - docker build -t sarvagnan/multi-nginx ./nginx
  - docker build -t sarvagnan/multi-server ./server
  - docker build -t sarvagnan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_ID"
  - echo "$DOCKER_PASSWORD"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push sarvagnan/multi-client
  - docker push sarvagnan/multi-nginx
  - docker push sarvagnan/multi-server
  - docker push sarvagnan/multi-worker
